# Generated by Django 4.1.3 on 2022-12-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_profilename'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilename',
            name='username',
            field=models.CharField(blank=True, default=True, max_length=100),
        ),
    ]
